export default SupportedCoins = {
  BTC: { image: 'example.png', name: 'Bitcoin' },
  XRP: { image: 'example.png', name: 'Ripple' },
  ETH: { image: 'example.png', name: 'Ethereum' },
  BTH: { image: 'example.png', name: 'Bitcoin Cash' },
  EOS: { image: 'example.png', name: 'Eos' },
  XLM: { image: 'example.png', name: 'Stellar Lumens' },
  USDT: { image: 'example.png', name: 'Tether' },
  LTC: { image: 'example.png', name: 'Litecoin' },
  TRX: { image: 'example.png', name: 'Tron' },
  BSV: { image: 'example.png', name: 'Bitcoin SV' },
  ADA: { image: 'example.png', name: 'Cardano' },
  IOTA: { image: 'example.png', name: 'Iota' },
  XMR: { image: 'example.png', name: 'Monero' },
  BNB: { image: 'example.png', name: 'Binance Coin' },
  DASH: { image: 'example.png', name: 'Dash' },
  NEM: { image: 'example.png', name: 'Nem' },
  NEO: { image: 'example.png', name: 'Neo' },
  ETC: { image: 'example.png', name: 'Ethereum Classic' },
  USDC: { image: 'example.png', name: 'USD Coin' },
  MKR: { image: 'example.png', name: 'Maker' },
  ZEC: { image: 'example.png', name: 'Z Cash' },
  WAVES: { image: 'example.png', name: 'Waves' },
  DOGE: { image: 'example.png', name: 'Dogecoin' },
  XTZ: { image: 'example.png', name: 'Texos' },
  VET: { image: 'example.png', name: 'VeChain' },
  BTG: { image: 'example.png', name: 'Bitcoin Gold' },
  ONT: { image: 'example.png', name: 'Ontology' },
  QTUM: { image: 'example.png', name: 'Qtum' },
  OMG: { image: 'example.png', name: 'OmiseGO' },
  ZIL: { image: 'example.png', name: 'Zilliqa' },
  ZRX: { image: 'example.png', name: '0x' },
  DCR: { image: 'example.png', name: 'Decred' },
  BAT: { image: 'example.png', name: 'Basic Attention Token' },
  LINK: { image: 'example.png', name: 'Chainlink' },
  LSK: { image: 'example.png', name: 'Lisk' },
  PAX: { image: 'example.png', name: 'Paxos Standard Token' },
  BCD: { image: 'example.png', name: 'Bitcoin Diamond' },
  BCN: { image: 'example.png', name: 'ByteCoin' },
  NANO: { image: 'example.png', name: 'Nano' },
  DGB: { image: 'example.png', name: 'DigiByte' },
  ICX: { image: 'example.png', name: 'Icon' },
  BTS: { image: 'example.png', name: 'BitShares' },
  XVG: { image: 'example.png', name: 'Verge' },
  SC: { image: 'example.png', name: 'Siacoin' },
  REP: { image: 'example.png', name: 'Augur' },
  R: { image: 'example.png', name: 'Revain' },
  GUSD: { image: 'example.png', name: 'Gemini Dollar' },
  AE: { image: 'example.png', name: 'Aeternity' },
  STRAT: { image: 'example.png', name: 'Stratis' }
};
